### ISSUE TITLE
Attribute ending in backslash fails formatting

### ISSUE THREAD

**Issue by FabianLauer** [FabianLauer/tsxml#11]
From https://github.com/FabianLauer/vs-code-xml-format/issues/6:

> An attribute like:
> 
> <absPath url="D:\Users\kgunders\Documents\MR\Projects\HyperLinkSheets\"
> 
> Will cause the following error:
> 
> XML formatting failed: at line 2, column 694: namespace prefix must be followed by a tag name.
> 
> Here is more context from the problematic XML:
> 
>     <Choice Requires="x15">
>         <absPath url="D:\Users\kgunders\Documents\MR\Projects\HyperLinkSheets\" xmlns:x15ac="http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac" />
>     </Choice>
> A work around is to temporarily add a character after the backslash, format, and remove the extra character.

**Comment by FabianLauer** [comment]
Fixed by commit 864fad3842eceb95.

**Comment by KarlGunderson** [comment]
New extension works great, thanks.

**Comment by FabianLauer** [comment]
Thanks for the feedback 😃
