### ISSUE TITLE
格式后换行问题

### ISSUE THREAD

**Issue by linjiyou** [FabianLauer/tsxml#18]
格式前
![image](https://user-images.githubusercontent.com/50936259/88753820-d9a1a780-d18f-11ea-80f6-26f247bc69a9.png)

 格式后
     
![image](https://user-images.githubusercontent.com/50936259/88753866-ee7e3b00-d18f-11ea-992f-2b12f296d0b2.png)

    如何才能不换行呢

**Comment by FabianLauer** [comment]
Closing as invalid. Asking to use English for tickets, thanks :-)
